site_name: Docs
site_url: https://odonnellrory.github.io/
repo_url: https://github.com/odonnellrory/odonnellrory.github.io
repo_name: odonnellrory/odonnellrory.github.io
edit_uri: blob/main/docs/         

# Configuration
theme:
  name: material
  custom_dir: docs/
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  - awesome-pages                  # auto order from .pages files
  - minify                         # smaller HTML
  - glightbox                      # for adding images
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - toc:
      permalink: true
  # Material “pymdownx” goodies
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist

use_directory_urls: true           # pretty URLs (/page/ instead of /page.html)
strict: true                       # fail builds on errors




extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/odonnellrory
